### ISSUE TITLE
Extract random patches from different volumes at same locations

### ISSUE THREAD

**Issue by MFaizyabAli** [fepegar/torchio-docs#1]
Hi, I am new to torchio and wanted to ask as to how we can extract random patches from two spatially related volumes at the same spatial locations, such that the patch pairs are related? Thank you

**Comment by fepegar** [comment]
Hi, @MFaizyabAli. I suggest you take a look at the [documentation](https://torchio.readthedocs.io/quickstart.html) and to the examples (at the bottom of that page). For more information, you can read the [documentation on patch-based training](https://torchio.readthedocs.io/data/patch_based.html).

I'm going to close this, as this repo is not the official one. Please use https://github.com/fepegar/torchio/ instead.
